# Generated by Django 4.1.7 on 2023-04-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_customer_cart_user_rename_customer_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, to='base.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='quantities',
            field=models.JSONField(default=list),
        ),
    ]
