# Generated by Django 4.1.7 on 2023-04-09 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_cart_product_remove_cart_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
